
version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  create-infrastructure:
    docker: 
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Create CF stack..."
          command: |
            aws cloudformation create-stack \
              --template-body file://cf-config.yml \
              --parameters file://cf-params.json \
              --stack-name stack-${CIRCLE_WORKFLOW_ID:0:5} \
              --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" \
              --region us-east-1
workflows:
  the-workflow:
    jobs:
      - create-infrastructure
