---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes
    
- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes 
    
- name: "Remove non-required deps"
  become: yes
  apt:
    autoremove: yes    

- name: "Install nodejs"
  become: yes
  apt:
    name: ["nodejs","npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Create server directory"
  file: 
    path: ~/web
    state: directory

- name: "Copy index test page"
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: "Start node server"
  shell: |
    pm2 start ~/web/index.js            